language: node_js
node_js:
- '8'
- '9'
script:
- npm install
- curl $GP_FAKE_BROKER > local-credentials.json
- if [[ $TRAVIS_NODE_VERSION == '8' ]]; then nyc npm test && nyc report --reporter=text-lcov
  | coveralls; else npm test; fi
env:
  global:
  - secure: fvzulZVjH3s1MjbmYL4qUvxI9NYq7AIt3ioPJC54fHgeHzINeDjvQFYtwVVSjTzeDsP/EcqdrTo8w9e8NRXJ/PUR17t6Q5Zlnvxj8VBPaqfZEK41RKf4CMnSTZwbPA/PHNGvmU5pu2646k+8ychnQ3jwkCDruVOBVCJwe3gRp0g=
cache:
  directories:
  - node_modules
  - ".nvm"
addons:
  coverity_scan:
    project:
      name: IBM-Bluemix/gp-js-client
      version: 1.0
      description: Globalization Pipeline Javascript SDK
    notification_email: srl295@gmail.com
    build_command_prepend: npm install
    build_command: "--no-command --fs-capture-search ./lib"
    branch_pattern: coverity_scan
# this is a comment
